# Generated by Django 5.0.3 on 2024-03-18 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_additionalskill_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalskill',
            name='description',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='date_range',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='description',
        ),
        migrations.RemoveField(
            model_name='language',
            name='level',
        ),
    ]
