# Generated by Django 5.0.3 on 2024-03-18 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_additionalskill_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalskill',
            name='description',
            field=models.TextField(default='Not specified'),
        ),
        migrations.AddField(
            model_name='experience',
            name='date_range',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='experience',
            name='description',
            field=models.TextField(default='Not specified'),
        ),
        migrations.AddField(
            model_name='language',
            name='level',
            field=models.CharField(default='Beginner', max_length=100),
        ),
    ]
